Parse unexported embedded option struct fields in Go 1.6 (consistent w/pre-Go 1.6)
Pre-Go 1.6, the newly added TestEmbeddedUnexported test passes. In Go
1.6beta1, it fails:

```
$ go test
--- FAIL: TestEmbedded (0.00s)
        assert_test.go:92: Unexpected parse error: unknown flag `v'
```

This commit makes the behavior consistent across Go versions.

Related: https://github.com/golang/go/issues/12367, specifically the
comments about how "code that assumes `f.PkgPath != nil` means a field
is unexported and must be ignored must now be revised to check for
`f.PkgPath != nil && !f.Anonymous` for it to walk into the embedded
structs to look for exported fields contained within."