Update to run go-flags on AIX
Without flag !aix, the library show the following error when you build to a cross environment aix/ppc64:
github.com/jessevdk/go-flags@v1.4.0/termsize.go:19:27: undefined: syscall.SYS_IOCTL